# -*- coding: utf-8 -*-
"""3023notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BHBjcKyeAD5sr494G9ETSCFZ-obOxZUN
"""

!pip install arch

"""## Philips Curve

"""

import arch
import matplotlib.pyplot as plt
plt.style.use("seaborn")

import pandas as pd
import numpy as np
import statsmodels.api as sm

"2021-12-12"

cpi = pd.read_csv("/content/drive/MyDrive/3023/CPIAUCSL.csv", index_col = 0, parse_dates = True)
mich_inflation = pd.read_csv("/content/drive/MyDrive/3023/MICH.csv", index_col = 0, parse_dates = True)
unemployment = pd.read_csv("/content/drive/MyDrive/3023/UNRATE.csv", index_col =0, parse_dates = True)
data = pd.concat([cpi, unemployment, mich_inflation], axis=1, join = 'inner')

type("2021-12-12")



data.to_csv("/content/drive/MyDrive/3023/dataset.csv")

from google.colab import drive
drive.mount('/content/drive')



def regression(data):

past_data = data[: "1984"]
current_data = data["2015":]

def plot_philips(data):

  dates = [x.timestamp() for x in data.index]
  plt.figure(figsize=(10, 8))
  plt.grid(True)
  plt.scatter(data['UNRATE'].values, data['CPIAUCSL_PC1'].values,
              c=dates, cmap='coolwarm', s=60, alpha=0.5)
  _ = plt.ylabel('Inflation Rate')
  _ = plt.xlabel('Unemployment Rate')
  plt.title('Scatterplot of Inflation against Unemployment')
  cbar = plt.colorbar()
  cbar.set_label('Date')
  plt.show()

plot_philips(data)

plot_philips(past_data)

import seaborn as sns
x1 = past_data[["UNRATE"]]
y1 = past_data[["CPIAUCSL_PC1"]]

sns.regplot(x1, y1)

import seaborn as sns
x2 = current_data[["UNRATE"]]
y2 = current_data[["CPIAUCSL_PC1"]]

sns.regplot(x2, y2)

data.head()

data.dtypes

